(()=>{
 const cfg=window.HK_ADMIN_CONFIG||{}; const api=(cfg.apiBase||'').replace(/\/$/,''); let token=sessionStorage.getItem('hk-admin-token')||''; let data=null;
 const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
 const status=(msg,bad=false)=>{const el=$('#saveState');if(el){el.textContent=msg;el.style.color=bad?'#e0a6a6':''}};
 const getPath=(o,p)=>p.split('.').reduce((a,k)=>a?.[k],o); const setPath=(o,p,v)=>{const a=p.split('.');let x=o;a.slice(0,-1).forEach(k=>x=x[k]??=( {} ));x[a.at(-1)]=v};
 function authHeaders(){return {'Authorization':'Bearer '+token,'Content-Type':'application/json'}}
 async function login(username,password){const r=await fetch(api+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||'Login failed');const j=await r.json();token=j.token;sessionStorage.setItem('hk-admin-token',token)}
 async function load(){status('جاري تحميل المحتوى...');const r=await fetch(api+'/api/content',{headers:authHeaders(),cache:'no-store'});if(r.status===401){logout();throw new Error('Session expired')}if(!r.ok)throw new Error('Load failed');data=await r.json();bind();renderCollections();$('#jsonEditor').value=JSON.stringify(data,null,2);status('جاهز')}
 function bind(){$$('[data-path]').forEach(el=>{el.value=getPath(data,el.dataset.path)??'';el.oninput=()=>{setPath(data,el.dataset.path,el.value);$('#jsonEditor').value=JSON.stringify(data,null,2);status('تعديلات غير منشورة')}})}
 const schemas={films:[['title.ar','العنوان عربي'],['title.en','Title English'],['type','النوع'],['year','السنة'],['description.ar','الوصف عربي','wide'],['description.en','Description English','wide'],['image','مسار الصورة','wide'],['url','الرابط','wide']],plugins:[['name','الاسم'],['type','النوع'],['version','الإصدار'],['platform','المنصة'],['host','Host'],['page','صفحة المنتج'],['description.ar','الوصف عربي','wide'],['description.en','Description English','wide'],['image','الصورة','wide'],['downloadMac','Download macOS','wide'],['downloadWindows','Download Windows','wide'],['manual','Manual URL','wide']],dctl:[['name','الاسم'],['type','النوع'],['description.ar','الوصف عربي','wide'],['description.en','Description English','wide'],['image','الصورة','wide'],['download','Download URL','wide']]};
 function renderCollections(){for(const type of ['films','plugins','dctl']){const root=$('#'+type+'Editor');if(!root)continue;root.innerHTML='';(data[type]||[]).forEach((item,i)=>{const card=document.createElement('div');card.className='collection-card';const head=document.createElement('div');head.className='collection-card-head';head.innerHTML=`<strong>${escapeHtml(item.name||item.title?.ar||item.title?.en||('Item '+(i+1)))}</strong><button type="button" class="btn ghost danger">حذف</button>`;head.querySelector('button').onclick=()=>{if(confirm('حذف هذا العنصر؟')){data[type].splice(i,1);renderCollections();syncJson();status('تعديلات غير منشورة')}};card.appendChild(head);const fields=document.createElement('div');fields.className='collection-fields';for(const [path,label,wide] of schemas[type]){const l=document.createElement('label');if(wide)l.classList.add('wide');l.textContent=label;const multiline=path.includes('description');const input=document.createElement(multiline?'textarea':'input');input.value=getPath(item,path)??'';input.dir=/\.en$|url|image|page|download|manual|host|platform|version/i.test(path)?'ltr':'auto';input.oninput=()=>{setPath(item,path,input.value);head.querySelector('strong').textContent=item.name||item.title?.ar||item.title?.en||('Item '+(i+1));syncJson();status('تعديلات غير منشورة')};l.appendChild(input);fields.appendChild(l)}card.appendChild(fields);root.appendChild(card)})}}
 function syncJson(){$('#jsonEditor').value=JSON.stringify(data,null,2)}
 async function publish(){try{status('جاري النشر...');const r=await fetch(api+'/api/content',{method:'PUT',headers:authHeaders(),body:JSON.stringify({content:data,message:'Update website content from HK Admin'})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Publish failed');status('تم النشر إلى GitHub. 4EVERLAND سيعيد النشر تلقائياً.')}catch(e){status(e.message,true)}}
 function logout(){token='';sessionStorage.removeItem('hk-admin-token');$('#dashboard').hidden=true;$('#loginView').hidden=false}
 function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
 $('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const ls=$('#loginStatus');ls.textContent='جاري الدخول...';try{if(!api||api.includes('YOUR-WORKER'))throw new Error('ضع رابط Cloudflare Worker في admin/config.js أولاً');await login($('#username').value,$('#password').value);$('#loginView').hidden=true;$('#dashboard').hidden=false;await load();ls.textContent=''}catch(err){ls.textContent=err.message}});
 $$('.admin-nav button').forEach(b=>b.onclick=()=>{$$('.admin-nav button').forEach(x=>x.classList.toggle('active',x===b));$$('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==b.dataset.tab)});
 $$('[data-add]').forEach(b=>b.onclick=()=>{const t=b.dataset.add;const blank=t==='films'?{id:'film-'+Date.now(),title:{ar:'فيلم جديد',en:'New Film'},type:'FILM',year:'',description:{ar:'',en:''},image:'assets/img/film-card.jpg',url:''}:t==='plugins'?{id:'plugin-'+Date.now(),name:'New Plugin',type:'OFX',version:'1.0.0',platform:'macOS / Windows',host:'DaVinci Resolve',description:{ar:'',en:''},image:'assets/img/plugin-card.jpg',page:'',downloadMac:'',downloadWindows:'',manual:''}:{id:'dctl-'+Date.now(),name:'New DCTL',type:'DCTL',description:{ar:'',en:''},image:'assets/img/dctl-card.jpg',download:''};data[t].push(blank);renderCollections();syncJson();status('تعديلات غير منشورة')});
 $('#applyJsonBtn').onclick=()=>{try{data=JSON.parse($('#jsonEditor').value);bind();renderCollections();status('تم تطبيق JSON محلياً — لم يتم النشر بعد')}catch(e){status('JSON غير صالح: '+e.message,true)}};
 $('#publishBtn').onclick=publish;$('#reloadBtn').onclick=()=>{if(confirm('إلغاء التعديلات غير المنشورة وإعادة التحميل؟'))load()};$('#logoutBtn').onclick=logout;
 if(token && api && !api.includes('YOUR-WORKER')){$('#loginView').hidden=true;$('#dashboard').hidden=false;load().catch(()=>logout())}
})();
