const te=new TextEncoder();
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=UTF-8',...headers}})}
function cors(env,req){const origin=req.headers.get('Origin')||'';const allowed=(env.ALLOWED_ORIGIN||'').split(',').map(x=>x.trim()).filter(Boolean);return {'access-control-allow-origin':allowed.includes(origin)?origin:(allowed[0]||origin),'access-control-allow-headers':'Authorization, Content-Type','access-control-allow-methods':'GET, PUT, POST, OPTIONS','vary':'Origin'}}
async function hmac(secret,text){const key=await crypto.subtle.importKey('raw',te.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,te.encode(text));return btoa(String.fromCharCode(...new Uint8Array(sig))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function b64url(s){return btoa(unescape(encodeURIComponent(s))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function unb64url(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return decodeURIComponent(escape(atob(s)))}
async function makeToken(env,user){const payload=b64url(JSON.stringify({u:user,exp:Date.now()+1000*60*60*4}));return payload+'.'+await hmac(env.SESSION_SECRET,payload)}
async function verify(env,req){const h=req.headers.get('Authorization')||'';if(!h.startsWith('Bearer '))return false;const t=h.slice(7);const [p,s]=t.split('.');if(!p||!s)return false;if((await hmac(env.SESSION_SECRET,p))!==s)return false;try{return JSON.parse(unb64url(p)).exp>Date.now()}catch{return false}}
async function gh(env,path,init={}){const url=`https://api.github.com/repos/${env.GITHUB_OWNER}/${env.GITHUB_REPO}/${path}`;const headers={'authorization':`Bearer ${env.GITHUB_TOKEN}`,'accept':'application/vnd.github+json','x-github-api-version':'2022-11-28','user-agent':'hk-admin-worker',...(init.headers||{})};return fetch(url,{...init,headers})}
export default {async fetch(req,env){const ch=cors(env,req);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:ch});const u=new URL(req.url);
 try{
  if(u.pathname==='/api/health')return json({ok:true},200,ch);
  if(u.pathname==='/api/login'&&req.method==='POST'){const body=await req.json();if(body.username!==env.ADMIN_USERNAME||body.password!==env.ADMIN_PASSWORD)return json({error:'Invalid credentials'},401,ch);return json({token:await makeToken(env,body.username)},200,ch)}
  if(!(await verify(env,req)))return json({error:'Unauthorized'},401,ch);
  if(u.pathname==='/api/content'&&req.method==='GET'){const r=await gh(env,`contents/data/content.json?ref=${encodeURIComponent(env.GITHUB_BRANCH||'main')}`);if(!r.ok)return json({error:'GitHub read failed'},502,ch);const j=await r.json();const text=decodeURIComponent(escape(atob(j.content.replace(/\n/g,''))));return new Response(text,{headers:{'content-type':'application/json;charset=UTF-8',...ch}})}
  if(u.pathname==='/api/content'&&req.method==='PUT'){const body=await req.json();const content=body.content;if(!content||typeof content!=='object')return json({error:'Invalid content'},400,ch);const metaR=await gh(env,`contents/data/content.json?ref=${encodeURIComponent(env.GITHUB_BRANCH||'main')}`);if(!metaR.ok)return json({error:'Unable to read current file'},502,ch);const meta=await metaR.json();const encoded=btoa(unescape(encodeURIComponent(JSON.stringify(content,null,2)+'\n')));const save=await gh(env,'contents/data/content.json',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({message:body.message||'Update website content from HK Admin',content:encoded,sha:meta.sha,branch:env.GITHUB_BRANCH||'main'})});if(!save.ok){const err=await save.text();return json({error:'GitHub publish failed',detail:err.slice(0,500)},502,ch)}const out=await save.json();return json({ok:true,commit:out.commit?.sha||null},200,ch)}
  return json({error:'Not found'},404,ch)
 }catch(e){return json({error:'Server error',detail:String(e.message||e)},500,ch)}}};
